### ISSUE TITLE
Dependencies installation failed

### ISSUE THREAD

**Issue by ans-qureshi** [luxonis/depthai-ros#14]
I get this error after running `sudo wget -qO- https://raw.githubusercontent.com/luxonis/depthai-ros/noetic-devel/install_dependencis.sh | bash
`

![image](https://user-images.githubusercontent.com/38855178/120429664-3a40d880-c38f-11eb-984a-0f94016893b9.png)

**Comment by ans-qureshi** [comment]
Issue resolved after replacing line 10 of depthai-ros/install_dependencis.sh i.e. `cmake --build build --target install` with `sudo cmake --build build --target install`

@saching13 could you make suitable changes please?

**Comment by saching13** [comment]
`sudo wget -qO- https://raw.githubusercontent.com/luxonis/depthai-ros/noetic-devel/install_dependencis.sh | bash`

This command is run with `sudo` so any command inside the file will run as root user. So, it is normally not necessary in any ubuntu.

**Comment by themarpe** [comment]
@saching13 @ans-qureshi I think that the issue here is that the `sudo` applies to `wget` but not to `bash` command.
One option would be to do: 
```
sudo bash -c 'wget -qO- https://raw.githubusercontent.com/luxonis/depthai-ros/noetic-devel/install_dependencis.sh | bash'
```
or maybe just 
```
wget -qO- https://raw.githubusercontent.com/luxonis/depthai-ros/noetic-devel/install_dependencis.sh | sudo bash
```

Other dependencies work as expected as they do `sudo` in their own script for commands that need it.
So could also just drop `sudo` from the installation command:
```
wget -qO- https://raw.githubusercontent.com/luxonis/depthai-ros/noetic-devel/install_dependencis.sh | bash
``` 
And then do `sudo` in the script itself which need it (namely - installing to `/usr/local`, the aftermentioned `sudo cmake --build build --target install` by @ans-qureshi)

**Comment by saching13** [comment]
Hhmm. Makes sense. Will fix it. 
I am not sure why I didn't experience it or why other users didn't report this.
