### ISSUE TITLE
how to publish 400P color image for OV9782 camera(oak-d-sr)?

### ISSUE THREAD

**Issue by lturing** [luxonis/depthai-ros#620]
when i set the 400p resolution(depthai_ros_driver/config/oak_d_sr.yaml), and publish the color-scale image, meet the followed error:  
```
[component_container-2] [19443010C18B782700] [1.2] [1.840] [ColorCamera(3)] [warning] Unsupported resolution set for detected camera OV9782, needs 800_P or 720_P. Defaulting to 800_P
[component_container-2] [19443010C18B782700] [1.2] [1.840] [ColorCamera(0)] [warning] Unsupported resolution set for detected camera OV9782, needs 800_P or 720_P. Defaulting to 800_P

```

if i set 800p, it will work, but the fps cannot reach 20, so i need publish 400p and reach higher publishing rate

**Comment by Serafadam** [comment]
Hi, although resolution on the sensor itself is limited, since those are color cameras you can try using ISP scaling to rescale the final image, more information on that can be found [here](https://docs.luxonis.com/software/ros/depthai-ros/driver/#DepthAI%20ROS%20Driver-Setting%20RGB%20parameters) . You can use [this](https://docs.google.com/spreadsheets/d/153yTstShkJqsPbkPOQjsVRmM8ZO3A6sCqm7uayGF-EE/edit?gid=0#gid=0) document to calculate which scaling would fit best your solution (set resolution width/height, options with fields all green will be the best ones). You can also use `low_bandwidth` parameter to transfer compressed images.
